name: Moulinette
on:
  push:
  issue:
    types: [created, labeled, unlabeled, closed, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: "./"
      with:
        labels:
          - published
